# render.yaml
services:
  - type: web
    name: fastapi-streaming
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
